
- name: Disable Node.js module using dnf
  hosts: backend
  become: yes  # Use become if you need elevated privileges
  tasks:
    - name: Disable the nodejs module
      ansible.builtin.command:  dnf module disable nodejs -y

    - name: Disable the nodejs module
      ansible.builtin.command:  dnf module enable nodejs:20 -y 

    - name: Install MySQL server
      ansible.builtin.package:
        name: nodejs
        state: present  

    - name: Create user 'expense'
      ansible.builtin.user:
        name: expense
        state: present

    - name: Ensure the directory /path/to/directory exists
      ansible.builtin.file:
        path: /app
        state: directory   


    - name: Download file from URL
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip

        dest:   /tmp/backend.zip 
        
