- name: Install MySQL Server using the package module
  hosts: frontend
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Install MySQL server
      ansible.builtin.service:
        name: nginx
        state: started   
        enabled: yes

    - name: Remove a directory
      ansible.builtin.file:
       path: /usr/share/nginx/html  # Directory path to be removed
       state: absent  # Ensures the directory is removed
    

    - name: create directory
      ansible.builtin.file:
       path: /usr/share/nginx/html  # Directory path to be removed
       state: directory  # Ensures the directory is removed

    - name: Download file from URL
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip

        dest:   /tmp/frontend.zip   



    - name: Extract an archive
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip  # Path to the archive file
        dest: /usr/share/nginx/html  # Directory where the archive will be extracted
        remote_src: yes     


    - name: Copy a file to the remote host
      ansible.builtin.copy:
        src: expense.conf  # Local file to copy
        dest: /etc/nginx/default.d/expense.conf  # Destination path on the remote machine


    - name: restart
      ansible.builtin.service:
        name: nginx
        state: restarted     
     
    