
- name: Install MySQL Server using the package module
  hosts: mysql
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes    


    - name: Create the MySQL database
      community.mysql.mysql_db:
        name: mysql
        state: present
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql.daws83s.shop
